parameters:
    my_metadata_factory:   doctrine.orm.entity_manager


services:
    kif_doctrine_to_typescript.convert_command:
        class: Kif\DoctrineToTypescriptBundle\Command\ConvertCommand
        tags:
            -  { name: console.command }
        arguments: [ "@=service('doctrine.orm.entity_manager').getMetadataFactory().getAllMetadata()","@=container.has('jms_serializer') ? container.get('jms_serializer') : null" ]


