services:

    kif_doctrine_to_typescript.convert_command:
        class: Kif\DoctrineToTypescriptBundle\Command\ConvertCommand
        tags:
            -  { name: console.command }
        arguments: [ "@doctrine.orm.entity_manager","@=container.has('jms_serializer') ? container.get('jms_serializer') : null" ]


